<a href="https://colab.research.google.com/github/LongC24/UVM_CS254_HW/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Python


For this course, we are going to use Jupyter notebook as our environment for developing Python code.
refer to https://jupyter.readthedocs.io/en/latest/content-quickstart.html for the instructions on how to install it. The easiest way is to install from Anaconda (https://www.anaconda.com/download/) website, make sure you install with Python 3.7 or above.

Also, it is good for the students who are not familiar with python (or they need a quick refreshment) to follow Jim Bagrow tutorial http://bagrow.com/ds1/whirlwindtourpython/00-Title.html. 

All the assignments need to be written in Python 3.7 or above and can be run using Jupyter on Chrome, Safari or Firefox. These are the browsers that officially supported by jupyter.

<u> Note: for this assignment, submit your local copy of this page, running on IPython.The extension of the file is .ipynb. Don't submit if it is not the extention of your file. Submit the file to Blackboard under Assignment1 using this file format:</u> <b>Yourfirstname_lastname_Assignment1.ipynb. Marks might be deducted if you do not follow the submission steps.</b> 




# Assignment 1

##### Always import the needed libraries in the first cell as it is a good coding practice

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

# Assignment 1 -- Part 1

### Part 1, Q1  --  [8 pts]

1. Use the np.linspace function to create a row vector called Points containing exactly 499 values with values evenly spaced between -1 and 1.

2. What is the value at index 53?

In [ ]:
#Your code here



### Part 1, Q2  --  [8 pts]

For a given array x of 3x3 dimensions, convert this array into a one-dimensional array.

Hint 1 :  The output should be [1 2 3 4 5 6 7 8 9].

Hint 2: To get the dimension of an array, we use shape property. The dimension of the resulted array should be 1x9.


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print(x.shape)

#Your code here


(3, 3)


### Part 1, Q3  --  [8 pts]

Create an 10 x 10 array of zeros and then "frame" it with a border of ones(The framed array's size should be 10x10).

In [ ]:
#Your code here



### Part 1, Q4  --  [8 pts]


Create an 8 x 8 array with a checkerboard pattern of zeros and ones using for loop or vstack.
The expected output is given below:
      <h4> [[1, 0, 1, 0, 1, 0, 1, 0],</h4>
      <h4> [0, 1, 0, 1, 0, 1, 0, 1], </h4>
      <h4> [1, 0, 1, 0, 1, 0, 1, 0], </h4>
      <h4> [0, 1, 0, 1, 0, 1, 0, 1], </h4>
      <h4> [1, 0, 1, 0, 1, 0, 1, 0], </h4>
      <h4> [0, 1, 0, 1, 0, 1, 0, 1], </h4>
      <h4> [1, 0, 1, 0, 1, 0, 1, 0], </h4>
      <h4> [0, 1, 0, 1, 0, 1, 0, 1]] </h4>
      
      

In [ ]:
#Your code here



### Part 1, Q5  --  [8 pts]

Create a function which creates an n×n array with the value of (i,j)-entry equal to i+j.Here i is the index of row and j is the index of column. For example, if the index of i is 2 and the index of j is 5, then, the value of i+j will be 7.

In [ ]:
#Your code here


### Part 1, Q6  --  [8 pts]


Define a matrix(2D array) of 100x100 and initialize this matrix by its row index. After that, define a vector(1D array) of length 100 and initialize this vector by the index of the element.

Now, Use the dot function on a vector-vector, matrix-vector and matrix-matrix example. you can define your own dot function or use any build in functions. Dot function should peform dot product of two arrays (in this case between 2D and 1D array).

Hint: One way of doing this is to use np.dot() function.
You can have a look at this link: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

In [ ]:
#Your code here


### Part 1, Q7  --  [8 pts]

 For a given random 3x5 array using the np.random.randint() function,
 compute (without using for loop): the sum of all the entries, the sum of the rows and the sum of the columns. 

In [ ]:
arr = np.random.randint(50, size=(3, 5))

# Your code here


### Part 1, Q8  --  [8 pts]
In this question, a 5x5 array has been created using np.random.randint(). The goal is to sort(ascending) all the rows using the second column. To be more precise,to sort the rows, we will use the values from column 2.
Lets say you have an array like below:

[[46 36 40 40 25]

 [43  3 17 23  4]
 
 [43 39  7  9  4]
 
 After the sorting, you will have output like below:
 
 [43  3 17 23  4]
 
 [46 36 40 40 25]
 
 [43 39  7  9  4]
 

Hint: You can use argsort function. It is just a way. You can follow other way if you want.

In [ ]:
x = np.random.randint(50, size=(5, 5))

print('Unsorted:\n{}\n'.format(x))
#Your code here


#--------------------
print('Rows sorted by the second column:\n{}'.format(x))

Unsorted:
[[ 1 47 28  8 15]
 [45  7  2 22 34]
 [30 11 31 11 43]
 [31  2 41 33 45]
 [44 41 34 14 45]]

Rows sorted by the second column:
[[ 1 47 28  8 15]
 [45  7  2 22 34]
 [30 11 31 11 43]
 [31  2 41 33 45]
 [44 41 34 14 45]]


# Assignment 1 -- Part 2
For part 2, you will be using the Breast Cancer Wisconsin (Diagnostic) Database to create a classifier that can help diagnose patients. First, read through the description of the dataset (below).

In [ ]:
from sklearn.datasets import load_breast_cancer

The object returned by load_breast_cancer() is a scikit-learn Bunch object, which is similar to a dictionary, for information about dictionary refer to http://bagrow.com/ds1/whirlwindtourpython/07-Built-in-Data-Structures.html

In [ ]:
cancer = load_breast_cancer()
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
cancer['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
cancer['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
cancer['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
cancer['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

### Part 2, Q1  --  [8 pts]
How many features does the breast cancer dataset have? 
Hint :This function should return an integer.

In [ ]:
#Your code here


### Part 2, Q2  --  [7 pts]

Scikit-learn is machine learning library for the Python programming language. It uses dataframe as a primary data container just like excel uses csv. hence, you need to convert the sklearn.dataset to DataFrame.

Convert the sklearn.dataset cancer to a DataFrame.

Hint: This function should return a (569, 31) DataFrame with
columns =

['mean radius', 'mean texture', 'mean perimeter', 'mean area',
'mean smoothness', 'mean compactness', 'mean concavity',
'mean concave points', 'mean symmetry', 'mean fractal dimension',
'radius error', 'texture error', 'perimeter error', 'area error',
'smoothness error', 'compactness error', 'concavity error',
'concave points error', 'symmetry error', 'fractal dimension error',
'worst radius', 'worst texture', 'worst perimeter', 'worst area',
'worst smoothness', 'worst compactness', 'worst concavity',
'worst concave points', 'worst symmetry', 'worst fractal dimension',
'target']

In [ ]:
#Your code here


### Part 2, Q3  --  [7 pts]

What is the class distribution? (i.e. how many instances of malignant (encoded 0) and how many benign (encoded 1)?)
This function should return a Series of length 2 with integer values and index = ['malignant', 'benign']

In [ ]:
#Your code here



### Part 2, Q4  --  [7 pts]

Split the DataFrame into X (the data) and y (the labels).

This function should return a tuple of length 2: (X, y), where

- X has shape (569, 30)
- y has shape (569,).

for more information about tuple refer to http://bagrow.com/ds1/whirlwindtourpython/07-Built-in-Data-Structures.html

In [ ]:
#Your code here



### Part 2, Q5  --  [7 pts]
Plot the histogram of 'malignant' and 'benign'.

Histogram is way to show the frequency of a set of continuous data. In this case, there are 2 labels ('malignant' and 'benign').The name of the labels will be in the x-axis and the frequency count of those labels will be in the y-axis.

You can find more about Histogram here:

https://statistics.laerd.com/statistical-guides/understanding-histograms.php

In [ ]:
#Your code here

